use_frameworks!

inhibit_all_warnings!
#设置一个声明的pods集，注意在命名的时候需用share开头
def share_RainKit_pods
    pod 'MMDrawerController'
    pod 'SDWebImage', '~> 4.2.3'
    pod 'Masonry', '~> 1.1.0'
    pod 'YYModel', '~> 1.0.4'
    pod 'AFNetworking'
    pod 'Aspects', '~> 1.4.1'
    pod 'IQKeyboardManager'
    pod 'WHKit'
    pod 'Aspects', '~> 1.4.1'
end

target 'RainKit_Example' do
  pod 'RainKit', :path => '../'
  share_RainKit_pods
 target 'RainKit_Tests' do
    inherit! :search_paths

    
  end
end
